### ISSUE TITLE
Extra bundle

### ISSUE THREAD

**Issue by ildar2** [Pkmmte/PkRSS#27]
Some feeds attach their image in extras. Is there a way to get that image?
I noticed Bundle extras property in Article, but it never used.

**Comment by enrichman** [comment]
Could you provide an example with an url or a snippet?

**Comment by Pkmmte** [comment]
@ildar2 Originally, the "extras" field in the Article class were used for custom data you wanted. 

This was a bad decision on my part because it coupled custom data incorrectly and was difficult to cache. PkRSS 2.0 will remove this field.

Still, that's unrelated to image extras you mention. Do you have an example URL?

**Comment by ildar2** [comment]
I honestly don't remember, we ended up aggregating feeds on the server and feeding sorted news to clients. I might been referring to tag enclosure (like in http://www.inform.kz/rss/rus.xml) which is present or more likely tag media:group (like in https://www.nur.kz/rss/all.rss) which is not there
